services:
  postgres-dev:
    image: postgres:17
    container_name: postgres-db-dormConnect
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "dormConnect"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data

volumes:
  postgres_data_dev: