spring:
  application:
    name: dormConnect
  datasource:
    url: jdbc:postgresql://localhost:5434/dormConnect
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  ai:
    ollama:
      chat:
        options:
          model: tinyllama
      embedding:
        enabled: true
        options:
          model: nomic-embed-text
server:
  port: 8091