
-- Usuń stare ograniczenia jeśli trzeba
ALTER TABLE grouped_rooms_entity
    ALTER COLUMN id DROP DEFAULT;

-- Zmień kolumnę na IDENTITY
ALTER TABLE grouped_rooms_entity
    ALTER COLUMN id
        ADD GENERATED BY DEFAULT AS IDENTITY;
