CREATE TABLE common_room
(
    common_room_id                       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    common_room_type                     SMALLINT,
    capacity                             INTEGER,
    floor                                INTEGER,
    hours_of_time_windows                INTEGER,
    how_many_times_a_week_you_can_use_it INTEGER,
    is_active                            BOOLEAN,
    CONSTRAINT pk_common_room PRIMARY KEY (common_room_id)
);
