CREATE TABLE floor
(
    floor_id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    floor_number INTEGER,
    rooms        BIGINT[],
    common_rooms BIGINT[],
    CONSTRAINT pk_floor PRIMARY KEY (floor_id)
);

DROP TABLE dorm_rooms_room_assigns CASCADE;

DROP TABLE grouped_rooms_entity_rooms CASCADE;