spring:
  application:
    name: security-service
  datasource:
    url: jdbc:postgresql://localhost:5434/dormConnect
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  ai:
    openai:
      api-key: your_openai_api_key_here
server:
  port: 8091
  cloud:
    config:
      server:
        git:
          uri: https://github.com/centGeek/DormConnect.git
          default-label: main
          clone-on-start: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka