CREATE TABLE dorm_forms
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id        BIGINT                                  NOT NULL,
    start_date     date                                    NOT NULL,
    end_date       date                                    NOT NULL,
    is_processed   BOOLEAN                                 NOT NULL,
    comments       VARCHAR(500),
    priority_score INTEGER                                 NOT NULL,
    CONSTRAINT pk_dorm_forms PRIMARY KEY (id)
);

