CREATE TABLE dorm_problem
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    student_id     BIGINT                                  NOT NULL,
    description    VARCHAR(255),
    problem_date   date,
    problem_status VARCHAR(255),
    CONSTRAINT pk_dorm_problem PRIMARY KEY (id)
);