CREATE TABLE room_replacement_forms
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    requester_id   BIGINT,
    target_student BIGINT,
    requester_room BIGINT,
    target_room    BIGINT,
    status         VARCHAR(255)                NOT NULL,
    created_at     TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    responded_at   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_room_replacement_forms PRIMARY KEY (id)
);
CREATE SEQUENCE IF NOT EXISTS room_replacement_forms_seq START WITH 1 INCREMENT BY 50;
