CREATE TABLE common_room
(
    common_room_id                       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    common_room_type                     VARCHAR(255),
    capacity                             INTEGER,
    floor                                INTEGER,
    max_time_you_can_stay                INTEGER,
    how_many_times_a_week_you_can_use_it INTEGER,
    is_active                            BOOLEAN,
    CONSTRAINT pk_common_room PRIMARY KEY (common_room_id)
);