CREATE TABLE common_room_assignment
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    common_room_id BIGINT,
    archived       BOOLEAN                                 NOT NULL,
    start_date     TIMESTAMP WITHOUT TIME ZONE,
    end_date       TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_common_room_assignment PRIMARY KEY (id)
);

CREATE TABLE common_room_assignment_users
(
    common_room_assignment_entity_id BIGINT NOT NULL,
    users_user_id                    BIGINT NOT NULL
);

ALTER TABLE common_room_assignment
    ADD CONSTRAINT FK_COMMON_ROOM_ASSIGNMENT_ON_COMMON_ROOM FOREIGN KEY (common_room_id) REFERENCES common_room (common_room_id);

ALTER TABLE common_room_assignment_users
    ADD CONSTRAINT fk_comrooassuse_on_common_room_assignment_entity FOREIGN KEY (common_room_assignment_entity_id) REFERENCES common_room_assignment (id);

ALTER TABLE common_room_assignment_users
    ADD CONSTRAINT fk_comrooassuse_on_user_entity FOREIGN KEY (users_user_id) REFERENCES user_profile (user_id);
