CREATE TABLE common_room_assigment
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    room_id    BIGINT,
    archived   BOOLEAN                                 NOT NULL,
    start_date TIMESTAMP WITHOUT TIME ZONE,
    end_date   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_commonroomassigment PRIMARY KEY (id)
);

CREATE TABLE common_room_assigment_users
(
    common_room_assigment_id BIGINT NOT NULL,
    users_user_id            BIGINT NOT NULL
);

ALTER TABLE common_room_assigment
    ADD CONSTRAINT FK_COMMONROOMASSIGMENT_ON_ROOM FOREIGN KEY (room_id) REFERENCES dorm_rooms (id);

ALTER TABLE common_room_assigment_users
    ADD CONSTRAINT fk_comrooassuse_on_common_room_assigment FOREIGN KEY (common_room_assigment_id) REFERENCES common_room_assigment (id);

ALTER TABLE common_room_assigment_users
    ADD CONSTRAINT fk_comrooassuse_on_user_entity FOREIGN KEY (users_user_id) REFERENCES user_profile (user_id);