#define SDA_PIN 21
#define SCL_PIN 22
#define NTAG216_MEMORY_BLOCKS 231
#define DATA_BLOCK_SIZE 4
#define NTAG216_UID_SIZE 7
#define USER_UUID_SIZE_BYTES 16
#define USER_UUID_START_PAGE 5
#define USER_UUID_START_NUMBER 0xFE
#define USER_UUID_STOP_NUMBER 0xFF
#define USER_UUID_CONTROL_BYTE_NUMBER 2
#define USER_UUID_TOTAL_BYTES 


#define WORKING_OUTPUT_PIN 2