CREATE TABLE common_room_assignment
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    common_room_id BIGINT,
    users_id       BIGINT[],
    archived       BOOLEAN                                 NOT NULL,
    start_date     TIMESTAMP WITHOUT TIME ZONE,
    end_date       TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_common_room_assignment PRIMARY KEY (id)
);

ALTER TABLE common_room_assignment
    ADD CONSTRAINT FK_COMMON_ROOM_ASSIGNMENT_ON_COMMON_ROOM FOREIGN KEY (common_room_id) REFERENCES common_room (common_room_id);