CREATE TABLE nfc_device
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "uuid" UUID,
    room_number     varchar(255),
    device_status   varchar(255),
    lock_status     varchar(255),
    ip_address      varchar(255),
    mac_address     varchar(255),

    CONSTRAINT nfc_programmer_pk PRIMARY KEY (id)
);