CREATE TABLE nfc_programmer
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "uuid" UUID,
    "port"     varchar(255),
    ip_address   varchar(255),
    device_status     varchar(255),

    CONSTRAINT nfc_device_pk PRIMARY KEY (id)
);