CREATE TABLE dorm_rooms
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    number   VARCHAR(255),
    capacity INTEGER                                 NOT NULL,
    floor    INTEGER                                 NOT NULL,
    active   BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_dormrooms PRIMARY KEY (id)
);