spring:
  application:
    name: dormConnect
  datasource:
    url: jdbc:postgresql://localhost:5434/dormConnect
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  ai:
    openai:
      api-key: <your-api-key>
      chat:
        options:
          model: gpt-4
          temperature: 0.5
          max-tokens: 800
          top-p: 1
          frequency-penalty: 0
      embedding:
        options:
          model: text-embedding-3-large
server:
  port: 8091