CREATE TABLE dorm_rooms_room_assigns
(
    room_entity_id  BIGINT NOT NULL,
    room_assigns_id BIGINT NOT NULL,
    CONSTRAINT uc_dorm_rooms_room_assigns_roomassigns UNIQUE (room_assigns_id),
    CONSTRAINT fk_dorroorooass_on_room_assign_entity FOREIGN KEY (room_assigns_id) REFERENCES room_assign_entity (id),
    CONSTRAINT fk_dorroorooass_on_room_entity FOREIGN KEY (room_entity_id) REFERENCES dorm_rooms (id)
);

CREATE TABLE grouped_rooms_entity
(
    id         BIGINT NOT NULL,
    group_name VARCHAR(255),
    CONSTRAINT pk_groupedroomsentity PRIMARY KEY (id)
);

CREATE TABLE grouped_rooms_entity_rooms
(
    grouped_rooms_entity_id BIGINT NOT NULL,
    rooms_id                BIGINT NOT NULL,
    CONSTRAINT uc_grouped_rooms_entity_rooms_rooms UNIQUE (rooms_id),
    CONSTRAINT fk_grorooentroo_on_grouped_rooms_entity FOREIGN KEY (grouped_rooms_entity_id) REFERENCES grouped_rooms_entity (id),
    CONSTRAINT fk_grorooentroo_on_room_entity FOREIGN KEY (rooms_id) REFERENCES dorm_rooms (id)
);

CREATE TABLE room_assign_entity
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    room_id     BIGINT,
    resident_id BIGINT,
    from_date   date                                    NOT NULL,
    to_date     date,
    CONSTRAINT pk_roomassignentity PRIMARY KEY (id),
    CONSTRAINT FK_ROOMASSIGNENTITY_ON_ROOM FOREIGN KEY (room_id) REFERENCES dorm_rooms (id)
);


ALTER TABLE dorm_rooms
    ADD CONSTRAINT FK_DORMROOMS_ON_GROUPEDROOMS FOREIGN KEY (grouped_rooms_id) REFERENCES grouped_rooms_entity (id),
    ALTER COLUMN number SET NOT NULL,
    ADD CONSTRAINT uc_dormrooms_number UNIQUE (number),
    ADD grouped_rooms_id BIGINT;
