CREATE TABLE event
(
    event_id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_name       VARCHAR(255),
    description      VARCHAR(1000),
    start_date_time  TIMESTAMP WITHOUT TIME ZONE,
    end_date_time    TIMESTAMP WITHOUT TIME ZONE,
    location         VARCHAR(255),
    event_type       VARCHAR(255),
    max_participants INTEGER,
    image_url        VARCHAR(255),
    CONSTRAINT pk_event PRIMARY KEY (event_id)
);

CREATE TABLE event_organizer_id
(
    event_event_id BIGINT NOT NULL,
    organizer_id   BIGINT
);

CREATE TABLE event_participant_id
(
    event_event_id BIGINT NOT NULL,
    participant_id BIGINT
);

ALTER TABLE event_organizer_id
    ADD CONSTRAINT fk_event_organizerid_on_event FOREIGN KEY (event_event_id) REFERENCES event (event_id);

ALTER TABLE event_participant_id
    ADD CONSTRAINT fk_event_participantid_on_event FOREIGN KEY (event_event_id) REFERENCES event (event_id);