server:
  port: 8091

spring:
  application:
    name: auth-user-service
  datasource:
    url: jdbc:postgresql://localhost:5434/auth_users_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true
    locations: classpath:db/migration

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  secret: tajny_klucz_tajny_klucz_tajny_klucz