server:
  port: 8000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  security:
    user:
      name: disabled
      password: disabled
  cloud:
    gateway:
      routes:
        - id: auth
          uri: lb://AUTH-USER-SERVICE
          predicates:
            - Path=/auth/api/auth/**,/auth/register/**,/auth/v3/api-docs/**
          filters:
            - RewritePath=/auth/(?<segment>.*), /${segment}
        - id: event
          uri: lb://EVENT-SERVICE
          predicates:
            - Path=/event/api/event/administrate/**,/event/api/event/administrate,/event/v3/api-docs/**
          filters:
            - RewritePath=/event/(?<segment>.*), /${segment}

springdoc:
  api-docs:
    gateway:
      enabled: true
      locations:
        - http://localhost:8081/v3/api-docs
        - http://localhost:8091/v3/api-docs

  swagger-ui:
    urls:
      - name: AUTH-USER-SERVICE
        url: /auth/v3/api-docs
      - name: EVENT-SERVICE
        url: /event/v3/api-docs